import Head from "next/head";
import React from "react";
import Layout from "src/components/Layout";
export default function Dishes() {
  return (
    <>
      <Head>
        <title>Liên hệ</title>
        <link
          rel="icon"
          href="/icons/logoIcon.png"
          type="image/png"
          sizes="30x30"
        />
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout>Dishes</Layout>
    </>
  );
}
