import { Button, useColorMode } from "@chakra-ui/react";
import Head from "next/head";
import Layout from "src/components/Layout";
import Banner from "src/components/Section/Banner";
import { createClient } from "contentful";
import About from "src/components/Section/About";

export default function Home({ dishes }) {
  const { colorMode, toggleColorMode } = useColorMode();
  console.log(dishes);
  return (
    <div>
      <Head>
        <title>Trang chủ</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Layout>
        <Banner />
        <About />
        <div className="container">
          <Button onClick={toggleColorMode}>
            Toggle {colorMode === "light" ? "Dark" : "Light"}
          </Button>
        </div>
      </Layout>
    </div>
  );
}

export async function getStaticProps() {
  const client = createClient({
    space: process.env.CONTENTFUL_SPACE_ID,
    accessToken: process.env.CONTENTFUL_ACCESS_TOKEN
  });
  const res = await client.getEntries({ content_type: "dishes" });
  console.log("res", res);
  return {
    props: {
      dishes: res.items
    }
  };
}
