import { Button, useColorMode } from "@chakra-ui/react";
import Head from "next/head";
import Layout from "src/components/Layout";
import Banner from "src/components/Section/Banner";
import About from "src/components/Section/About";
import BestDishes from "src/components/Section/BestDishes";
import { client } from "src/helpers/contentful";

export default function Home({ dishes }) {
  const { colorMode, toggleColorMode } = useColorMode();
  return (
    <>
      <Head>
        <title>Trang chủ</title>
        <link
          rel="icon"
          href="/icons/logoIcon.png"
          type="image/png"
          sizes="30x30"
        />
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Layout>
        <Banner />
        <About />
        <BestDishes dishes={dishes} />
        <div className="container">
          <Button onClick={toggleColorMode}>
            Toggle {colorMode === "light" ? "Dark" : "Light"}
          </Button>
        </div>
      </Layout>
    </>
  );
}
export async function getStaticProps() {
  const res = await client.getEntries({ content_type: "dishes" });
  console.log("res", res);
  return {
    props: {
      dishes: res.items
    }
  };
}
