import Head from "next/head";
import Layout from "src/components/Layout";
import About from "src/components/Section/About";
import Banner from "src/components/Section/Banner";
import BestDishes from "src/components/Section/BestDishes";
import Info from "src/components/Section/Info";
import { client } from "src/helpers/contentful";

export default function Home({ dishes }) {
  return (
    <>
      <Head>
        <title>Trang chủ</title>
        <link
          rel="icon"
          href="/icons/logoIcon.png"
          type="image/png"
          sizes="30x30"
        />
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Layout>
        <Banner />
        <Info />
        <BestDishes dishes={dishes} />
        <About />
      </Layout>
    </>
  );
}
export async function getStaticProps() {
  const res = await client.getEntries({ content_type: "dishes" });
  return {
    props: {
      dishes: res.items
    }
  };
}
